defaults:
  - model: uca8_realman_ring2
  - data: realman_ring2_multisource_count
  - feature: stft_16k
  - train: realman_multisource_count
  - runtime: local
  - _self_

experiment_name: realman_ring2_multisource_count
seed: 42
